# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: inyl labs
email: indurluv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  © 2016-2018 inyl.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://inyl.github.io/" # the base hostname & protocol for your site
tagline: Web Developer
#twitter_username: jekyllrb
github_username:  inyl
#highlighter: pygments
name : 송DEV
gems:
  - jekyll-paginate

paginate: 7
paginate_path: '/page/:num/'
# Build settings
markdown: kramdown
#theme: minima
disqus: inyl
#gems:
#  - jekyll-paginate
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

recommend:
  /programming/2017/09/14/http_component:
    - /programming/2016/10/22/macos_git
    - /search_engine/2017/05/01/tkt_elasticsearch
    - /programming/2018/05/06/springboot2_api_2
  /seminar/2016/11/12/hanbit_2016:
    - /devops/2016/08/20/devops
    - /book/2017/04/25/book_review_1
    - /book/2018/02/15/book_review_2
  /programming/2017/04/19/tuple:
    - /programming/2017/10/21/java9_jshell
    - /book/2017/04/25/book_review_1
    - /devops/2016/08/20/devops
  /programming/2017/05/05/slf4j:
    - /devops/2016/08/20/devops
    - /programming/2017/10/21/java9_jshell
    - /search_engine/2017/05/01/tkt_elasticsearch
  /programming/2018/03/10/springboot2_api:
    - /programming/2018/05/06/springboot2_api_2
    - /programming/2017/08/11/cnn_image_search
    - /programming/2016/10/15/JHipster
  /programming/2017/06/03/lucene_index_type:
    - /devops/2016/08/20/devops
    - /book/2017/04/25/book_review_1
    - /github/2017/01/21/github_newsletter
  /programming/2017/07/31/opencv_image_color_cluster:
    - /programming/2017/08/11/cnn_image_search
    - /programming/2018/05/06/springboot2_api_2
    - /search_engine/2017/04/18/bm25_2
  /programming/2017/08/30/dynamo_ttl:
    - /programming/2017/08/25/mac_crontab
    - /programming/2017/12/02/timeout
    - /programming/2016/10/22/macos_git
  /book/2018/02/15/book_review_2:
    - /seminar/2016/11/12/hanbit_2016
    - /devops/2016/08/20/devops
    - /book/2017/04/25/book_review_1
  /machine_learning/2017/03/04/think_tensorflow:
    - /programming/2017/08/25/mac_crontab
    - /programming/2016/10/22/macos_git
    - /search_engine/2017/05/01/tkt_elasticsearch
  /programming/2017/05/15/webpack2_babel:
    - /search_engine/2017/02/18/solr_learning_to_rank
    - /search_engine/2017/05/01/tkt_elasticsearch
    - /programming/2017/08/25/mac_crontab
  /programming/2017/05/09/database:
    - /programming/2017/02/04/circuit_breaker
    - /programming/2017/09/27/compact_string
    - /github/2017/01/21/github_newsletter
  /programming/2016/10/15/JHipster:
    - /github/2017/01/21/github_newsletter
    - /machine_leaning/2016/10/01/dl4j_word2vec_exam
    - /programming/2018/03/10/springboot2_api
  /machine_leaning/2016/12/31/ML_for_give_up_on_math_1:
    - /seminar/2016/11/12/hanbit_2016
    - /devops/2016/08/20/devops
    - /programming/2017/12/02/timeout
  /programming/2017/12/02/timeout:
    - /devops/2016/08/20/devops
    - /programming/2017/08/30/dynamo_ttl
    - /book/2018/02/15/book_review_2
  /programming/2017/09/27/compact_string:
    - /programming/2017/09/05/visualvm_plugin_install_fail
    - /search_engine/2017/04/01/bm25
    - /search_engine/2017/05/01/tkt_elasticsearch
  /machine_leaning/2016/10/01/dl4j_word2vec_exam:
    - /programming/2017/08/25/mac_crontab
    - /github/2017/01/21/github_newsletter
    - /programming/2016/10/22/macos_git
  /programming/2018/05/06/springboot2_api_2:
    - /programming/2018/03/10/springboot2_api
    - /programming/2017/05/15/webpack2_babel
    - /programming/2017/05/11/java_stream
  /programming/2017/08/11/cnn_image_search:
    - /programming/2017/07/31/opencv_image_color_cluster
    - /search_engine/2017/05/01/tkt_elasticsearch
    - /programming/2018/03/10/springboot2_api
  /search_engine/2017/05/01/tkt_elasticsearch:
    - /programming/2017/08/25/mac_crontab
    - /programming/2017/05/15/webpack2_babel
    - /programming/2017/09/27/compact_string
  /programming/2016/10/22/macos_git:
    - /programming/2017/08/25/mac_crontab
    - /blog/2016/08/28/jekyll_github_page
    - /devops/2016/08/20/devops
  /programming/2017/10/21/java9_jshell:
    - /programming/2017/04/19/tuple
    - /programming/2017/05/05/slf4j
    - /programming/2016/10/22/macos_git
  /programming/2017/09/05/visualvm_plugin_install_fail:
    - /programming/2016/10/22/macos_git
    - /programming/2017/09/27/compact_string
    - /blog/2016/08/28/jekyll_github_page
  /programming/2017/08/25/mac_crontab:
    - /programming/2016/10/22/macos_git
    - /blog/2016/08/28/jekyll_github_page
    - /programming/2017/08/30/dynamo_ttl
  /devops/2016/08/20/devops:
    - /seminar/2016/11/12/hanbit_2016
    - /programming/2017/12/02/timeout
    - /programming/2016/10/22/macos_git
  /blog/2016/08/28/jekyll_github_page:
    - /programming/2017/08/25/mac_crontab
    - /programming/2016/10/22/macos_git
    - /programming/2017/09/05/visualvm_plugin_install_fail
  /book/2017/04/25/book_review_1:
    - /seminar/2016/11/12/hanbit_2016
    - /devops/2016/08/20/devops
    - /book/2018/02/15/book_review_2
  /programming/2017/02/04/circuit_breaker:
    - /seminar/2016/11/12/hanbit_2016
    - /programming/2017/09/27/compact_string
    - /programming/2017/09/05/visualvm_plugin_install_fail
  /search_engine/2017/02/18/solr_learning_to_rank:
    - /programming/2017/05/15/webpack2_babel
    - /programming/2017/08/25/mac_crontab
    - /search_engine/2017/04/18/bm25_2
  /search_engine/2017/04/01/bm25:
    - /search_engine/2017/04/18/bm25_2
    - /programming/2017/09/27/compact_string
    - /programming/2017/05/15/webpack2_babel
  /search_engine/2017/04/18/bm25_2:
    - /search_engine/2017/04/01/bm25
    - /search_engine/2017/02/18/solr_learning_to_rank
    - /programming/2017/07/31/opencv_image_color_cluster
  /github/2017/01/21/github_newsletter:
    - /devops/2016/08/20/devops
    - /book/2017/04/25/book_review_1
    - /blog/2016/08/28/jekyll_github_page
  /programming/2017/05/11/java_stream:
    - /devops/2016/08/20/devops
    - /programming/2018/05/06/springboot2_api_2
    - /programming/2017/09/05/visualvm_plugin_install_fail
